---
- hosts: qavserver
  become: yes
  ignore_errors: yes
    tasks:
      - name: install package
        package:
          name: "{{ item }}"
          state: present
      with_items:
        - unzip
        - wget
        - httpd
     
          
       
